### ISSUE TITLE
[gatsby-plugin-matomo] Register page views correctly

### ISSUE THREAD

**Issue by jeanfredrik** [whitespace-se/gatsby-packages#28]
Page views are registered as events now and page context is not set properly. This needs to be addressed

**Comment by degeer** [comment]
Use the following url:
https://whitespace.analys.co/js/container_fh3MwuUb.js

Data should be displayed on this page:
https://whitespace.analys.co/index.php?module=CoreHome&action=index&idSite=9&period=range&date=previous7#?idSite=9&period=range&date=previous7&category=General_Visitors&subcategory=Live_VisitorLog

Additional 
- [ ] Add config to disable tracking: `_paq.push(["setDoNotTrack", true]);`
